Algoritmo "Exercicio-07"
// 
//  
// Descrição   : Crie um algoritmo que leia um número real e mostre na tela o seu dobro e a
//sua terça parte.
// Autor(a)    : Daiana Simao
// Data atual  : 23/06/2022
Var
   Valor,terco,dobro:Real
Inicio
   Escreva("Digite um numero: ")
   Leia(Valor)
   dobro<-Valor*2
   terco<-Valor/3
   EscrevaL("O dobro de ",valor," é ",dobro)
   EscrevaL("O terco de ",valor," é ",terco)
Fimalgoritmo