Algoritmo "semnome"
// 
//  
// Descrição   :  Desenvolva um algoritmo que leia dois números inteiros e mostre o somatório
//entre eles.
// Autor(a)    : Daiana Simao
// Data atual  : 23/06/2022
Var
   N1,N2,Soma:Inteiro
Inicio
      Escreva("Digite um valor: ")
      Leia(N1)
      Escreva("Digite outro valor: ")
      Leia(N2)
      Soma<-(N1+N2)
      Escreva("A soma entre ",N1," e ",N2," é igual a ",Soma)
Fimalgoritmo