Algoritmo "AntecessorESucessor"
//
//
// Descrição   : Faça um programa que leia um número inteiro e mostre o seu antecessor e seu
// sucessor.)
// Autor(a)    :Daiana Simão
// Data atual  : 23/06/2022
Var
   num,ant,suc:Inteiro

Inicio
      Escreva("Digite um numero: ")
      Leia(num)
      ant<-num-1
      Escreval("O antecessor de ",num," e igual a ",ant)
      suc<-num+1
      Escreval("O sucessor de ",num," e igual a ",suc)



Fimalgoritmo