Algoritmo "Delta"
//
//
// Descrição   : Desenvolva uma lógica que leia os valores de A, B e C de uma equação do
//segundo grau e mostre o valor de Delta
// Autor(a)    : Daiana Simão
// Data atual  : 23/06/2022

Var
a,b,c,delta:Real
Inicio
      Escreva("O valor de A: ")
      Leia(a)
      Escreva("O valor de B: ")
      Leia(b)
      Escreva("O valor de C: ")
      Leia(c)
      delta<-(b*b)-(4*a*c)
      Escreva("O valor de delta e ",delta)
      
      
Fimalgoritmo
