Algoritmo "Salario com Sequencia Basica"
// 
//  
// Descrição   : Crie um programa que leia o nome e o salario do funcionario, mostrando no final uma mensagem
// Autor(a)    : Daiana simão
// Data atual  : 21/06/2022
Var
   Nome:Caractere  // Seção de Declarações das variáveis
   Salario:Real
Inicio
      Escreva("Nome do funcionario: ")
      Leia(Nome)
      Escreva("Salario: ")
      Leia(Salario)
      EscrevaL("O funcionario ",Nome," tem um salario de R$",Salario," em junho")
Fimalgoritmo