Algoritmo "Numero impar e par"
//
//
// Descrição   : Desenvolva um programa que leia um número inteiro e mostre se ele é PAR ou
//ÍMPAR.
// Autor(a)    : Daiana Simão
// Data atual  : 23/06/2022
Var
   num:Inteiro

Inicio
   Escreva("Digite um numero: ")
   Leia(num)
   se(num%2=0)entao
      Escreval("O numero ",num," e PAR")
   senao
      Escreval("O Nunmero ",num," e IMPAR")
   fimse
Fimalgoritmo